error: the Depends field contains an arch-specific dependency but the package is architecture all
(cherry picked from commit 203d207d3d4bdaa4ee0d8006d8fa9158222d0a3f)